# Generated by Django 3.0.5 on 2020-04-27 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='description',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='title',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='hospital',
            name='Name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='isoFree',
            field=models.BigIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='isoTotal',
            field=models.BigIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='pin',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='uptime',
            field=models.TimeField(auto_now=True),
        ),
    ]
