# Generated by Django 3.0.5 on 2020-04-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_auto_20200427_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Contact',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Name',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='isoFree',
            field=models.BigIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='isoTotal',
            field=models.BigIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pin',
            field=models.TextField(default='0'),
        ),
    ]
